name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        # Github Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        buildplat:
          - [ ubuntu-22.04, manylinux1_x86_64 ]
          - [ windows-2022, win_amd64 ]
          - [ macos-15, macosx_15_0_arm64 ]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3

    - name: Install OpenMP (via Homebrew) for macOS
      if: runner.os == 'macOS'
      run: |
        brew install libomp

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user --upgrade setuptools wheel twine build Cython numpy

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel --plat-name=${{ matrix.buildplat[1] }}
    - name: Upload distributions
      uses: actions/upload-artifact@v4
      with:
        name: release-dists-${{ matrix.buildplat[1] }}-${{ matrix.python-version }}
        path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/rankfmc

    strategy:
      matrix:
        buildplat:
          - [ ubuntu-22.04, manylinux1_x86_64 ]
          - [ windows-2022, win_amd64 ]
          - [ macos-15, macosx_15_0_arm64 ]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists-${{ matrix.buildplat[1] }}-${{ matrix.python-version }}
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
